tasks:
  - name: Open files
    command: gp open "NiceGUI - Hello World/app/main.py"

  - name: NiceGUI
    command: cd "NiceGUI - Hello World/app" && pip install nicegui && python3 main.py

  - name: Shell
    command: cd "NiceGUI - Hello World/app" && ls
    openMode: split-right