tasks:
  - name: Open files
    command: gp open "NiceGUI - Hello World/app/main.py"

  - name: NiceGUI
    init: pip install nicegui

  - name: Start
    command: cd "NiceGUI - Hello World/app" && python3 main.py
    openMode: split-right