tasks:
  - name: Open files
    command: gp open README.md && gp open app/main.py

  - name: NiceGUI
    init: pip install nicegui

  - name: Start
    command: cd "NiceGUI - Hello World/app" && python3 main.py
    openMode: split-right