version: "3.9"

services:
  nicegui:
      image: zauberzeug/nicegui:latest
      restart: always
      ports:
          - 80:8080
      volumes:
          - ./app:/app/    
      environment:
          #- PUID=1000 # change this to your user id
          #- PGID=1000 # change this to your group id
          - STORAGE_SECRET="change-this-to-yor-own-private-secret"
      command: "python3 ${APP-main.py}"